/** pagination limit */
export const LIMIT: 100;
/** array max-items */
export const MAX_ITEMS: 10000;
export const MINUTE: 60000;
export const HOUR: number;
export const DAY: number;
export const OBJECT: "object";
export const ARRAY: "array";
export const STRING: "string";
export const NUMBER: "number";
export const BOOLEAN: "boolean";
export const INTEGER: "integer";
