version: "3"
services:
  mariadb:
    image: docker.io/library/mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=example

  # see https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker-mac.html#start-a-single-node-cluster
  cockroach:
    image: docker.io/cockroachdb/cockroach:latest
    ports:
      - "26257:26257"
      - "8080:8080"
    environment:
      # - COCKROACH_DATABASE=/cockroach/cockroach-data
      - COCKROACH_USERCOCK=root
      - ROACH_PASSWORD=example
    command: start-single-node --advertise-addr 'localhost' --insecure

  postgres:
    image: docker.io/library/postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example

  mongodb:
    image: docker.io/library/mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

networks:
  hostnet:
    external: true
    name: host