version: "3"
services:
  mariadb:
    # https://hub.docker.com/_/mariadb
    image: docker.io/library/mariadb:11.1
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${SQLDB_PASSWORD}

  # see https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker-mac.html#start-a-single-node-cluster
  cockroach:
    # https://hub.docker.com/r/cockroachdb/cockroach
    image: docker.io/cockroachdb/cockroach:latest-v23.1
    ports:
      - "26257:26257"
      - "8080:8080"
    environment:
      # - COCKROACH_DATABASE=/cockroach/cockroach-data
      - COCKROACH_USERCOCK=${SQLDB_USER:-root}
      - ROACH_PASSWORD=${SQLDB_PASSWORD}
    command: start-single-node --advertise-addr 'localhost' --insecure

  postgres:
    # https://hub.docker.com/_/postgres
    image: docker.io/library/postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${SQLDB_USER:-root}
      - POSTGRES_PASSWORD=${SQLDB_PASSWORD}

  mongodb:
    # https://hub.docker.com/_/mongo
    image: docker.io/library/mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

networks:
  hostnet:
    external: true
    name: host
