openapi: '3.0.2'
info:
  version: '1.0'
  title: restbase
servers:
  - url: https://api.server.test/v1
paths:
  /:
    get:
      responses:
        '200':
          description: OK
    post:
      responses:
        '201':
          description: Created
  /{id}:
    get:
      responses:
        '200':
          description: OK
    put:
      responses:
        '200':
          description: OK
    delete:
      responses:
        '204':
          description: No Content

